---
# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: all
  disable:
    - depguard
    - nlreturn
    - wsl
  settings:
    errcheck:
      exclude-functions:
        - (github.com/jackc/pgx/v5.Tx).Commit
        - (github.com/jackc/pgx/v5.Tx).Rollback
        - (io.Closer).Close
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
        - pattern: ^log\.Print.*$
        - pattern: ^slog\.(Debug|Warn|Info|Error)$
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - ws *websocket.Conn
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
