// Code generated by "enumer -type=Method"; DO NOT EDIT.

package padoval

import (
	"fmt"
	"strings"
)

const _MethodName = "MethodGETMethodHEADMethodPATCHMethodPOSTMethodPUTMethodDELETEMethodQUERY"

var _MethodIndex = [...]uint8{0, 9, 19, 30, 40, 49, 61, 72}

const _MethodLowerName = "methodgetmethodheadmethodpatchmethodpostmethodputmethoddeletemethodquery"

func (i Method) String() string {
	if i < 0 || i >= Method(len(_MethodIndex)-1) {
		return fmt.Sprintf("Method(%d)", i)
	}
	return _MethodName[_MethodIndex[i]:_MethodIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MethodNoOp() {
	var x [1]struct{}
	_ = x[MethodGET-(0)]
	_ = x[MethodHEAD-(1)]
	_ = x[MethodPATCH-(2)]
	_ = x[MethodPOST-(3)]
	_ = x[MethodPUT-(4)]
	_ = x[MethodDELETE-(5)]
	_ = x[MethodQUERY-(6)]
}

var _MethodValues = []Method{MethodGET, MethodHEAD, MethodPATCH, MethodPOST, MethodPUT, MethodDELETE, MethodQUERY}

var _MethodNameToValueMap = map[string]Method{
	_MethodName[0:9]:        MethodGET,
	_MethodLowerName[0:9]:   MethodGET,
	_MethodName[9:19]:       MethodHEAD,
	_MethodLowerName[9:19]:  MethodHEAD,
	_MethodName[19:30]:      MethodPATCH,
	_MethodLowerName[19:30]: MethodPATCH,
	_MethodName[30:40]:      MethodPOST,
	_MethodLowerName[30:40]: MethodPOST,
	_MethodName[40:49]:      MethodPUT,
	_MethodLowerName[40:49]: MethodPUT,
	_MethodName[49:61]:      MethodDELETE,
	_MethodLowerName[49:61]: MethodDELETE,
	_MethodName[61:72]:      MethodQUERY,
	_MethodLowerName[61:72]: MethodQUERY,
}

var _MethodNames = []string{
	_MethodName[0:9],
	_MethodName[9:19],
	_MethodName[19:30],
	_MethodName[30:40],
	_MethodName[40:49],
	_MethodName[49:61],
	_MethodName[61:72],
}

// MethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MethodString(s string) (Method, error) {
	if val, ok := _MethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Method values", s)
}

// MethodValues returns all values of the enum
func MethodValues() []Method {
	return _MethodValues
}

// MethodStrings returns a slice of all String values of the enum
func MethodStrings() []string {
	strs := make([]string, len(_MethodNames))
	copy(strs, _MethodNames)
	return strs
}

// IsAMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Method) IsAMethod() bool {
	for _, v := range _MethodValues {
		if i == v {
			return true
		}
	}
	return false
}
